export type Provider='aws'|'azure'|'gcp'|'oracle'|'alibaba'|'ibm'|'digitalocean'|'custom';
export type Finding={_id?:string;externalId:string;provider:Provider;source:string;title:string;description:string;severity:'critical'|'high'|'medium'|'low'|'info';status:'open'|'in_progress'|'resolved'|'suppressed';resourceId:string;resourceName:string;region:string;cveIds:string[];remediation:string;lastSeen?:string;firstSeen?:string};
export type Connection={_id:string;provider:Provider;name:string;externalRef:string;regions?:string[];status:string;lastSync?:string;lastError?:string;createdAt?:string};
export type Advisory={cveId:string;source:string;title:string;description:string;severity:string;cvss?:number;knownExploited:boolean;vendorProject?:string;product?:string;publishedAt?:string;lastModified?:string;referenceUrls:string[]};
export type ProviderInfo={id:Provider;name:string;mode:'native'|'webhook'};
export type Session={user:null|{id:string;email:string;name:string;picture?:string;organizationId:string;provider:string};csrfToken:string;demoAllowed:boolean;providers:{google:boolean;microsoft:boolean}};
let csrf='';export async function request<T>(path:string,options:RequestInit={}){const headers=new Headers(options.headers);if(options.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(['POST','PATCH','PUT','DELETE'].includes(options.method??'GET')&&csrf)headers.set('x-csrf-token',csrf);const res=await fetch(`/api/v1${path}`,{...options,headers,credentials:'include'});if(res.status===204)return undefined as T;const body=await res.json().catch(()=>({error:`Request failed (${res.status})`}));if(!res.ok)throw new Error(body.error??`Request failed (${res.status})`);return body as T}
export async function getSession(){let failure:unknown;for(let attempt=0;attempt<4;attempt++){try{const value=await request<Session>('/auth/session');csrf=value.csrfToken;return value}catch(error){failure=error;if(attempt<3)await new Promise(resolve=>setTimeout(resolve,350*(attempt+1)))}}throw failure instanceof Error?failure:new Error('Could not connect to the CloudGuard API.')}
export async function demoLogin(){return request('/auth/demo',{method:'POST',body:'{}'})}
