import{GoogleAuth}from'google-auth-library';import type{CloudConnector,ConnectorInput,CloudFinding}from'./types.js';import{severity}from'./types.js';
export const gcpConnector:CloudConnector={provider:'gcp',label:'Google Cloud',async sync(input:ConnectorInput){
  const org=String(input.credentials.organizationId??input.externalRef),location=String(input.credentials.location??'global'),serviceAccount=String(input.credentials.serviceAccountJson??'');
  if(!org||!serviceAccount)throw new Error('Google Cloud needs an organization ID and service-account JSON with Security Center read access.');
  let credentials:unknown;try{credentials=JSON.parse(serviceAccount)}catch{throw new Error('Service-account JSON is not valid JSON.')}
  const auth=new GoogleAuth({credentials:credentials as any,scopes:['https://www.googleapis.com/auth/cloud-platform']}),client=await auth.getClient(),token=await client.getAccessToken();if(!token.token)throw new Error('Google Cloud did not issue an access token.');
  const parent=`organizations/${encodeURIComponent(org)}/sources/-/locations/${encodeURIComponent(location)}`,findings:CloudFinding[]=[];let pageToken='';
  do{const url=new URL(`https://securitycenter.googleapis.com/v2/${parent}/findings`);url.searchParams.set('filter','state="ACTIVE"');url.searchParams.set('pageSize','1000');if(pageToken)url.searchParams.set('pageToken',pageToken);const response=await fetch(url,{headers:{Authorization:`Bearer ${token.token}`}});if(!response.ok)throw new Error(`Security Command Center returned ${response.status}: ${await response.text()}`);const data=await response.json() as{listFindingsResults?:any[];nextPageToken?:string};for(const x of data.listFindingsResults??[]){const f=x.finding??{},r=x.resource??{};findings.push({externalId:f.name??`${f.category}:${r.name}`,provider:'gcp',source:'Google Security Command Center',title:f.category??'Cloud security finding',description:f.description??'',severity:severity(f.severity),status:f.state==='INACTIVE'?'resolved':'open',resourceId:r.name??'',resourceName:r.displayName??r.name?.split('/').pop()??'',region:r.location??'',cveIds:[f.vulnerability?.cve?.id].filter(Boolean),firstSeen:f.createTime?new Date(f.createTime):undefined,lastSeen:f.eventTime?new Date(f.eventTime):undefined,remediation:f.nextSteps??'',raw:x})}pageToken=data.nextPageToken??''}while(pageToken);
  return findings
}};
