import mongoose,{Schema,Types} from 'mongoose';
export const PROVIDERS=['aws','azure','gcp','oracle','alibaba','ibm','digitalocean','custom'] as const;
const UserSchema=new Schema({subject:{type:String,required:true},provider:{type:String,enum:['google','microsoft'],required:true},email:{type:String,required:true},name:{type:String,required:true},picture:String,organizationId:{type:Schema.Types.ObjectId,ref:'Organization',required:true}},{timestamps:true});UserSchema.index({provider:1,subject:1},{unique:true});
const OrganizationSchema=new Schema({name:{type:String,required:true},createdBy:{type:Schema.Types.ObjectId,ref:'User'}},{timestamps:true});
const ConnectionSchema=new Schema({organizationId:{type:Schema.Types.ObjectId,required:true,index:true},provider:{type:String,enum:PROVIDERS,required:true},name:{type:String,required:true},externalRef:{type:String,required:true},regions:[String],credentialsCiphertext:{type:String,select:false},webhookTokenHash:{type:String,select:false,index:true},status:{type:String,enum:['connected','pending','error'],default:'pending'},lastSync:Date,lastError:String},{timestamps:true});ConnectionSchema.index({organizationId:1,provider:1,externalRef:1},{unique:true});
const FindingSchema=new Schema({organizationId:{type:Schema.Types.ObjectId,required:true,index:true},connectionId:{type:Schema.Types.ObjectId,ref:'CloudConnection'},externalId:{type:String,required:true},provider:{type:String,enum:PROVIDERS,required:true},source:{type:String,required:true},title:{type:String,required:true},description:{type:String,default:''},severity:{type:String,enum:['critical','high','medium','low','info'],required:true},status:{type:String,enum:['open','in_progress','resolved','suppressed'],default:'open'},resourceId:{type:String,default:''},resourceName:{type:String,default:''},region:{type:String,default:''},cveIds:[String],firstSeen:Date,lastSeen:Date,remediation:{type:String,default:''},raw:{type:Schema.Types.Mixed}},{timestamps:true});FindingSchema.index({organizationId:1,source:1,externalId:1},{unique:true});FindingSchema.index({organizationId:1,severity:1,status:1});
const AdvisorySchema=new Schema({cveId:{type:String,required:true,unique:true},source:{type:String,required:true},title:String,description:{type:String,default:''},severity:{type:String,enum:['critical','high','medium','low','unknown'],default:'unknown'},cvss:Number,epss:Number,knownExploited:{type:Boolean,default:false},vendorProject:String,product:String,publishedAt:Date,lastModified:Date,referenceUrls:[String],raw:{type:Schema.Types.Mixed}},{timestamps:true});AdvisorySchema.index({knownExploited:1,lastModified:-1});AdvisorySchema.index({severity:1,publishedAt:-1});
const AuditSchema=new Schema({organizationId:{type:Schema.Types.ObjectId,required:true,index:true},actor:{type:String,required:true},action:{type:String,required:true},target:String,metadata:Schema.Types.Mixed},{timestamps:true});
export const User=mongoose.models.User||mongoose.model('User',UserSchema);export const Organization=mongoose.models.Organization||mongoose.model('Organization',OrganizationSchema);export const CloudConnection=mongoose.models.CloudConnection||mongoose.model('CloudConnection',ConnectionSchema);export const Finding=mongoose.models.Finding||mongoose.model('Finding',FindingSchema);export const Advisory=mongoose.models.Advisory||mongoose.model('Advisory',AdvisorySchema);export const AuditEvent=mongoose.models.AuditEvent||mongoose.model('AuditEvent',AuditSchema);
export type Provider=typeof PROVIDERS[number];export type FindingSeverity='critical'|'high'|'medium'|'low'|'info';export type AuthUser={id:string;email:string;name:string;picture?:string;organizationId:string;provider:string};export const oid=(value:string)=>new Types.ObjectId(value);

