import {Router,Request,Response} from 'express';import {randomBytes} from 'node:crypto';import * as oidc from 'openid-client';import {env,isDemo} from '../config.js';import {Organization,User,AuthUser} from '../models/index.js';
export const authRouter=Router();const configs=new Map<string,Promise<oidc.Configuration>>();
function providerConfig(provider:'google'|'microsoft'){if(configs.has(provider))return configs.get(provider)!;const id=provider==='google'?env.GOOGLE_CLIENT_ID:env.MICROSOFT_CLIENT_ID,secret=provider==='google'?env.GOOGLE_CLIENT_SECRET:env.MICROSOFT_CLIENT_SECRET;if(!id||!secret)throw new Error(`${provider} OAuth is not configured. Add its client ID and secret to server/.env.`);const issuer=provider==='google'?'https://accounts.google.com':`https://login.microsoftonline.com/${env.MICROSOFT_TENANT_ID}/v2.0`;const task=oidc.discovery(new URL(issuer),id,secret);configs.set(provider,task);return task}
const redirectFor=(p:'google'|'microsoft')=>p==='google'?env.GOOGLE_REDIRECT_URI:env.MICROSOFT_REDIRECT_URI;
authRouter.get('/session',(req,res)=>{if(!req.session.csrfToken)req.session.csrfToken=randomBytes(32).toString('hex');res.json({user:req.session.user??null,csrfToken:req.session.csrfToken,demoAllowed:isDemo,providers:{google:Boolean(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET),microsoft:Boolean(env.MICROSOFT_CLIENT_ID&&env.MICROSOFT_CLIENT_SECRET)}})});
for(const provider of ['google','microsoft'] as const){authRouter.get(`/${provider}`,async(req,res,next)=>{try{const config=await providerConfig(provider),verifier=oidc.randomPKCECodeVerifier(),challenge=await oidc.calculatePKCECodeChallenge(verifier),state=oidc.randomState(),nonce=oidc.randomNonce();req.session.oidc??={};req.session.oidc[provider]={state,nonce,verifier,createdAt:Date.now()};const url=oidc.buildAuthorizationUrl(config,{redirect_uri:redirectFor(provider),response_type:'code',scope:'openid email profile',code_challenge:challenge,code_challenge_method:'S256',state,nonce});await new Promise<void>((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));res.redirect(url.href)}catch(e){next(e)}});
authRouter.get(`/${provider}/callback`,async(req,res,next)=>{try{const tx=req.session.oidc?.[provider];if(!tx||Date.now()-tx.createdAt>10*60_000)throw new Error('Sign-in expired. Start again.');delete req.session.oidc?.[provider];const config=await providerConfig(provider),callbackUrl=new URL(req.originalUrl,env.API_URL),tokens=await oidc.authorizationCodeGrant(config,callbackUrl,{pkceCodeVerifier:tx.verifier,expectedState:tx.state,expectedNonce:tx.nonce});const claims=tokens.claims();if(!claims?.sub)throw new Error('The identity provider did not return a verified subject.');const email=String(claims.email??claims.preferred_username??'');if(!email)throw new Error('No email address was provided by the identity provider.');const name=String(claims.name??claims.given_name??email.split('@')[0]),picture=typeof claims.picture==='string'?claims.picture:undefined;let dbUser=await User.findOne({provider,subject:claims.sub});if(!dbUser){const org=await Organization.create({name:`${name}'s workspace`});dbUser=await User.create({provider,subject:claims.sub,email,name,picture,organizationId:org._id});org.createdBy=dbUser._id;await org.save()}else{dbUser.email=email;dbUser.name=name;dbUser.picture=picture;await dbUser.save()}const user:AuthUser={id:String(dbUser._id),email:dbUser.email,name:dbUser.name,picture:dbUser.picture,organizationId:String(dbUser.organizationId),provider};req.session.user=user;await new Promise<void>((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));res.redirect(env.APP_URL)}catch(e){next(e)}})}
authRouter.post('/demo',(req,res,next)=>{if(!isDemo)return res.status(404).json({error:'Demo sign-in is disabled.'});const user={id:'demo-user',email:'analyst@cloudguard.local',name:'Cloud Security Analyst',organizationId:'demo-org',provider:'demo'};req.session.user=user;req.session.save(e=>e?next(e):res.json({user}))});
authRouter.post('/logout',(req,res,next)=>req.session.destroy(e=>e?next(e):(res.clearCookie('cloudguard.sid'),res.status(204).end())));
